# Operational agents (worker, politician, etc.)
from __future__ import annotations
from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional, Dict

class IndividualRole(str, Enum):
    POLITICIAN = "Politician"
    INDUSTRIALIST = "Industrialist"
    WORKER = "Worker"
    FARMER = "Farmer"
    MERCHANT = "Merchant"
    SCIENTIST = "Scientist"
    MILITARY = "Military"
    MEDIA = "Media"
    CLERGY = "Clergy"
    NGO = "NGO"  # Activism / ONG
    CRIME = "Crime"
    INTELLIGENCE = "Intelligence"  # Servicii secrete

class IndividualData(BaseModel):
    """Agent individual (fără LLM) – starea și efecte simple."""
    id: str
    role: IndividualRole
    class_id: str
    state_id: str
    skill: float = 0.5          # 0..1 – productivitate / competență
    loyalty: float = 0.5        # 0..1 – loialitate față de stat/clasă
    morale: float = 0.5         # 0..1 – dispoziție / satisfacție
    energy: float = 1.0         # 0..1 – resursă de acțiune pe tick
    last_action: Optional[str] = None
    traits: Dict[str, float] = Field(default_factory=dict)  # extensii specifice

    def apply_fatigue(self, delta: float) -> None:
        """
        Tool: Apply fatigue to the agent, reducing energy.
        Parameters:
            delta (float): Amount of fatigue to apply
        Returns:
            None
        """
        self.energy = max(0.0, self.energy - max(0.0, delta))

    def recover(self, delta: float) -> None:
        """
        Tool: Recover energy for the agent.
        Parameters:
            delta (float): Amount of energy to recover
        Returns:
            None
        """
        self.energy = min(1.0, self.energy + max(0.0, delta))

    def adjust_morale(self, delta: float) -> None:
        """
        Tool: Adjust the morale of the agent.
        Parameters:
            delta (float): Change in morale
        Returns:
            None
        """
        self.morale = min(1.0, max(0.0, self.morale + delta))

    def set_action(self, name: str) -> None:
        """
        Tool: Set the last action performed by the agent.
        Parameters:
            name (str): Name of the action
        Returns:
            None
        """
        self.last_action = name

    # Efecte micro (deterministe, simple)
    def produce_output(self) -> float:
        """
        Tool: Produce output for the agent in a tick.
        Parameters:
            None
        Returns:
            float: Amount produced based on skill, morale, and energy
        """
        output = max(0.0, self.skill * (0.5 + 0.5 * self.morale) * self.energy)
        self.apply_fatigue(0.15)  # cost de efort
        self.set_action("produce")
        return output

    def protest_pressure(self) -> float:
        """
        Tool: Calculate social protest pressure generated by the agent.
        Parameters:
            None
        Returns:
            float: Protest pressure value
        """
        base = 0.2 if self.role in {IndividualRole.WORKER, IndividualRole.NGO, IndividualRole.MEDIA} else 0.1
        pressure = base * (1.0 - self.morale) * (0.5 + 0.5 * (1.0 - self.loyalty))
        self.apply_fatigue(0.1)
        self.set_action("protest")
        return pressure

    def lobby_weight(self) -> float:
        """
        Tool: Calculate lobbying influence weight for the agent.
        Parameters:
            None
        Returns:
            float: Lobbying weight value
        """
        base = 0.25 if self.role in {IndividualRole.POLITICIAN, IndividualRole.INDUSTRIALIST, IndividualRole.CLERGY} else 0.1
        w = base * (0.5 + 0.5 * self.skill) * (0.5 + 0.5 * self.energy)
        self.apply_fatigue(0.07)
        self.set_action("lobby")
        return w

    def covert_impact(self) -> float:
        """
        Tool: Calculate covert impact (sabotage, espionage, censorship) for the agent.
        Parameters:
            None
        Returns:
            float: Covert impact value
        """
        base = 0.0
        if self.role in {IndividualRole.CRIME, IndividualRole.INTELLIGENCE, IndividualRole.MILITARY, IndividualRole.MEDIA}:
            base = 0.2
        impact = base * (0.3 + 0.7 * self.skill) * (0.4 + 0.6 * self.energy)
        self.apply_fatigue(0.2)
        self.set_action("covert")
        return impact

    def summary(self) -> dict:
        """
        Tool: Get a summary of the agent's current state.
        Parameters:
            None
        Returns:
            dict: Dictionary with id, role, morale, energy, loyalty, last_action
        """
        return {
            "id": self.id, "role": self.role, "morale": self.morale,
            "energy": self.energy, "loyalty": self.loyalty, "last_action": self.last_action
        }
